import type { Metadata } from "next";
import { Inter } from "next/font/google"; // 你的字体可能不一样，不用管
import "./globals.css";
// 👇 1. 引入组件
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "严选资源站",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {/* 👇 2. 把这一行加在这里 */}
        <Toaster />
      </body>
    </html>
  );
}
